name: taski
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_getit: ^2.0.0
  sqflite: ^2.2.0  
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.8.3
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: 5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
      - family: Urbanist
        fonts:
          - asset: assets/font/Urbanist-Black.ttf
          - asset: assets/font/Urbanist-Bold.ttf
          - asset: assets/font/Urbanist-ExtraBold.ttf
          - asset: assets/font/Urbanist-ExtraLight.ttf
          - asset: assets/font/Urbanist-Light.ttf
          - asset: assets/font/Urbanist-Medium.ttf
          - asset: assets/font/Urbanist-Regular.ttf
          - asset: assets/font/Urbanist-SemiBold.ttf
          - asset: assets/font/Urbanist-Thin.ttf

